name: Deploy With Force Push

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'デプロイ先を選択'
        required: true
        type: choice
        options:
          - development
          - integration
          - staging
          - production
      commit_id:
        description: 'コミットIDを指定してデプロイする(ブランチ指定の場合は空文字を入力)'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.commit_id }}

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Force Push to Environment Branch
      run: |
        git fetch --all
        git checkout $BRANCH
        git reset --hard ${{ github.ref }}
        git push origin $BRANCH --force-with-lease
      env:
        BRANCH: ${{ github.event.inputs.environment }}
