name: Deploy With Force Push

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment branch to force push'
        required: true
        type: choice
        options:
          - development
          - integration
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Check if Tag Exists
      id: check_tag
      run: |
        if git fetch --tags && git rev-parse --verify --quiet $TAG > /dev/null; then
          git push origin --quiet --delete $TAG
        fi
      env:
        TAG: v.1-${{ github.event.inputs.environment }}

    - name: Force Push to Environment Branch
      run: |
        git tag -f $TAG
        git push origin $TAG
      env:
        TAG: v.1-${{ github.event.inputs.environment }}
