name: Deploy With Force Push 2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'デプロイ先を選択'
        required: true
        type: choice
        options:
          - development
          - integration
          - staging
          - production
      commit_id:
        description: 'コミットIDを指定してデプロイする(ブランチ指定の場合は空文字を入力)'
        type: string
      is_production:
        description: '本番環境にデプロイする(以降の項目も入力する必要があります)'
        type: boolean
      version:
        description: 'バージョン'
        type: string
      previous_tag:
        description: '1つ前のリリースタグ(空文字の場合は自動決定)'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Check required inputs
        if: github.event.inputs.environment == 'production'
        run: |
          if [[ "$IS_PRODUCTION" != true || -z "$VERSION" ]]; then
            echo "Error: production, version, and last_tag inputs are required when environment is production"
            exit 1
          fi
        shell: bash
        env:
          IS_PRODUCTION: ${{ github.event.inputs.is_production }}
          VERSION: ${{ github.event.inputs.version }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_id }}
          ssh-key: ${{ secrets.PRIVATE_DEPLOY_KEY }}
          fetch-depth: 1

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Force Push to Environment Branch
        run: |
          git branch -f ${{ github.ref }}
          git fetch --all
          git checkout $BRANCH
          git reset --hard ${{ github.ref }}
          git push origin $BRANCH --force-with-lease
        env:
          BRANCH: ${{ github.event.inputs.environment }}

  tag:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.event.inputs.environment == 'production'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_id }}

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Generate release tag
        uses: actions/github-script@v7
        id: release-tag
        with:
          script: |
            const version = process.env.VERSION

            let preReleaseCount = 1
            let preReleaseTag

            while (true) {
              preReleaseTag = `v${version}-${String(preReleaseCount).padStart(3, '0')}`
              try {
                await github.rest.git.getRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: `tags/${preReleaseTag}`
                })
                preReleaseCount += 1
              } catch (error) {
                if (error.status === 404) {
                  break
                } else {
                  throw error
                }
              }
            }

            console.log(preReleaseTag)
            return preReleaseTag
          result-encoding: string
        env:
          VERSION: ${{ github.event.inputs.version }}

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Get previous tag
        if: github.event.inputs.previous_tag == null
        uses: actions/github-script@v7
        id: get-previous
        with:
          script: |
            const tags = await github.rest.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1
            })
            console.log(tags)
            return tags.data[0].name
          result-encoding: string

      - name: Push release tag
        run: |
          git tag ${{ steps.release-tag.outputs.result }}
          git push origin ${{ steps.release-tag.outputs.result }}

      - name: Generate release notes
        uses: actions/github-script@v7
        with:
          script: |
            const previousTag = process.env.PREVIOUS_TAG
            const releaseTag = process.env.RELEASE_TAG

            const releaseNotes = await github.rest.repos.generateReleaseNotes({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: releaseTag,
              previous_tag_name: previousTag
            });
            console.log(releaseNotes);

            const data = new Date().toLocaleDateString("ja-JP", { year: "numeric", month: "2-digit", day: "2-digit"})
            const title = `リリース(${releaseTag}) ${data}`

            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: releaseTag,
              name: title,
              body: releaseNotes.data.body,
            });
        env:
          PREVIOUS_TAG: ${{ steps.get-previous.outputs.result && steps.get-previous.outputs.result || github.event.inputs.previous_tag }}
          RELEASE_TAG: ${{ steps.release-tag.outputs.result }}
