name: Deploy With Force Push

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment branch to force push'
        required: true
        type: choice
        options:
          - development
          - development2
          - integration
          - integration2
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      # token: ${{ secrets.CUSTOM_PAT }}

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Force Push to Environment Branch
      run: |
        git fetch --all
        git checkout ${{ github.event.inputs.environment }}
        git reset --hard ${{ github.ref }}
        git push origin ${{ github.event.inputs.environment }} --force-with-lease
