name: Tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Generate release tag
        uses: actions/github-script@v7
        id: release-tag
        with:
          script: |
            const date = new Date()
            console.log(date)
            const year = date.getFullYear()
            const month = String(date.getMonth() + 1).padStart(2, '0')
            const day = String(date.getDate()).padStart(2, '0')

            let preReleaseCount = 1
            let preReleaseTag

            while (true) {
              preReleaseTag = `v${year}${month}${day}-${String(preReleaseCount).padStart(3, '0')}`
              try {
                await github.rest.git.getRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: `tags/${preReleaseTag}`
                })
                preReleaseCount += 1
              } catch (error) {
                if (error.status === 404) {
                  break
                } else {
                  throw error
                }
              }
            }

            console.log(preReleaseTag)
            return preReleaseTag
          result-encoding: string

      - name: Get previous tag
        uses: actions/github-script@v7
        id: get-previous
        with:
          script: |
            const tags = await github.rest.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1
            })
            console.log(tags)
            return tags.data[0].name
          result-encoding: string

      - name: Push release tag
        run: |
          git tag ${{ steps.release-tag.outputs.result }}
          git push origin ${{ steps.release-tag.outputs.result }}

      - name: Generate release notes
        uses: actions/github-script@v7
        with:
          script: |
            const previousTag = process.env.PREVIOUS_TAG
            const releaseTag = process.env.RELEASE_TAG

            const releaseNotes = await github.rest.repos.generateReleaseNotes({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: releaseTag,
              previous_tag_name: previousTag
            });
            console.log(releaseNotes);

            const data = new Date().toLocaleDateString("ja-JP", { year: "numeric", month: "2-digit", day: "2-digit"})

            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: releaseTag,
              body: releaseNotes.data.body,
            });
        env:
          PREVIOUS_TAG: ${{ steps.get-previous.outputs.result }}
          RELEASE_TAG: ${{ steps.release-tag.outputs.result }}
